In [1]:
import mysql.connector
import time
import getpass
from tqdm.auto import tqdm
import pyzbar.pyzbar as pyzbar
import pyqrcode
import cv2
import os
import numpy
import colorama
from colorama import Back, Style
colorama.init(autoreset=True)
#------ScanningFromWebCamera---------------------
conn = mysql.connector.connect(host="localhost",port=3306,user="root",password="",database="employeedatabase")
def scan():
	i = 0
	cap = cv2.VideoCapture(0)
	font = cv2.FONT_HERSHEY_PLAIN
	while True:
		ret,frame=cap.read()
		decode = pyzbar.decode(frame)
		for obj in decode:
			name=obj.data
			name2= name.decode()
			nn,ii,pp,dd = name2.split(' ')           
# 			db =mysql.connector.connect(host='localhost',user='root',password='',database="employeedatabase")
			c = conn.cursor()
			c.execute("CREATE TABLE IF NOT EXISTS Record(name TEXT(100),id int(10),phone_no int(10),dept TEXT(100),TimeofMArk timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP)")
			c.execute("INSERT INTO record(`name`,`id`,`phone_no`,`dept`) VALUES (%s,%s,%s,%s)",(nn,ii,pp,dd))
			conn.commit()
			conn.close()
# 			cv2.destroyAllWindows()

#database portions--------------------------------
			i=i+1
		cv2.imshow("QRCode",frame)
		cv2.waitKey(2)
		cv2.destroyAllWindows

#------CreateDatabaseForeEmployee------------------
def database():
# 	conn =mysql.connector.connect(host='localhost',user='root','',database="employeedatabase")
	c = conn.cursor()
	c.execute("CREATE TABLE IF NOT EXISTS all_record (employee_name TEXT(100),employee_id int(10),employee_contact int(10),employee_department TEXT(100))")
	conn.commit()
# 	conn.close()
database()

#------AddingNewUsers/Employee---------------------
def add_User():
	Li = []
	E_name=str(input("Please Enter Employee Name\n"))
	E_id=int(input("Please Enter Employee Id\n"))
	E_contac= int(input("Please enter Employee Contact No\n"))
	E_dept= input("Please enter Employee Department\n")
	Li.extend((E_name,E_id,E_contac,E_dept))
#-----using List Compression to convert a list to str--------------
	listToStr = ' '.join([str(elem) for elem in Li])
	#print(listToStr)
	print(Back.YELLOW + "Please Verify the Information")
	print("Employee Name       = "+ E_name)
	print("Employee ID         = "+ str(E_id))
	print("Employee Contact    = "+ str(E_contac))
	print("Employee Department = "+ E_dept)
	input("Press Enter to continue or CTRL+C to Break Operation")
# 	conn =mysql.connector.connect(host='localhost',user='root','',database="employeedatabase")
	c = conn.cursor()
	c.execute("INSERT INTO all_record(`employee_name`,`employee_id`,`employee_contact`,`employee_department`) VALUES(%s,%s,%s,%s)",(E_name,E_id,E_contac,E_dept))
	conn.commit()
# 	conn.close()
	qr= pyqrcode.create(listToStr)
	if not os.path.exists('./QrCodes'):
		os.makedirs('./QRCodes')
	qr.png("./QRCodes/" +E_name+ ".png",scale=8)
#--------------ViewDatabase------------------------
def viewdata():
# 	conn =mysql.connector.connect(host='localhost',user='root','',database="employeedatabase")
	c = conn.cursor()
	c.execute("SELECT * FROM Record")
	rows = c.fetchall()
	for row in rows:
		print(row)
# 	conn.close()
#----------AdminScreen-----------------------
def afterlogin():
	print("+------------------------------+")
	print("|  1- Add New Employee         |")
	print("|  2- Veiw Record              |")
	print("+------------------------------+")
	user_input = input("")
	if user_input == '1':
		add_User()
	if user_input == '2':
		viewdata()

#Login--------------------------------------
def login():
	print(Back.CYAN+ 'Please Enter Password :')
	print(Back.YELLOW+"QR Code Attendace System")
	password = getpass.getpass()
	if password =='aka':
		for i in tqdm(range(4000)):
			print("",end='\r')
		print("------------------------------------------------------------------------------------------------------------------------")
		print(Back.BLUE+"QR Code Attendace System")
		afterlogin()
	if password != 'aka':
		print("Invalid Password")
		login()



#-------MainPage----------------------------
def markattendance():
	print("+------------------------------+")
	print("|  1- Mark Attendance          |")
	print("|  2- Admin Login              |")
	print("+------------------------------+")
	user_input2 = input("")
	if user_input2== '1':
		scan()
	if user_input2 == '2':
		login()
        
markattendance()

+------------------------------+
|  1- Mark Attendance          |
|  2- Admin Login              |
+------------------------------+
1

OperationalError: MySQL Connection not available.

In [4]:
import mysql.connector
# conn =mysql.connector.connect(hos'localhost',3306,'root','',"employeedatabase")
conn = mysql.connector.connect(host="localhost",port=3306,user="root",password="",database="employeedatabase")

In [3]:
VALUES('"+E_name+"','E_id','E_contac','"+E_dept+"')

connection successfull